lucky_numbers = [4, 3, 8, 10, 15, 16, 23, 43]
friends = ["Kevin", "Karen", "Jim", "Oscar", "Toby"]

print(friends)
# friends.extend(lucky_numbers)
# print(friends)
friends.append("Creed")
print(friends)
friends.insert(1, "Kelly")
print(friends)
friends.remove("Jim")
print(friends)
# friends.clear()
# print(friends)
friends.pop()
print(friends)
print(friends.index("Oscar"))
print(friends.count("Toby"))
friends.sort()
print(friends)
lucky_numbers.sort()
print(lucky_numbers)
lucky_numbers.reverse()
print(lucky_numbers)
friends2 = friends.copy()
print(friends2)